apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pwc-task
  namespace: argocd
spec:
  description: 
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'