name: Infra CD

on:
  push:
    paths:
      - "terraform/**"
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-ci-dev:
    uses: ./.github/workflows/terraform-plan-env.yaml
    with:
      environment: dev
  terraform-cd-dev:
    uses: ./.github/workflows/terraform-apply-env.yaml
    needs: [terraform-ci-dev]
    with:
      environment: dev

  terraform-ci-prod:
    uses: ./.github/workflows/terraform-plan-env.yaml
    needs: [terraform-cd-dev]
    with:
      environment: prod
  terraform-cd-prod:
    uses: ./.github/workflows/terraform-apply-env.yaml
    needs: [terraform-ci-prod]
    with:
      environment: prod
